version: '3.3'

services:
  eshop.web:
    image: eshop.web
    build:
      context: ./../Eshop.Web
      dockerfile: Dockerfile
    ports:
    - "443:443"
    extra_hosts:
    - "ibmke.eu:0.0.0.0"

  dockerwintest:
    image: dockerwintest
    build:
      context: ./../dockerWinTest
      dockerfile: Dockerfile
